[book]
authors = ["Christian Beilschmidt <christian.beilschmidt@geoengine.de>"]
language = "en"
multilingual = false
src = "src"
title = "Geo Engine Docs"

[rust]
edition = "2021"

[output.html]
theme = "theme"
default-theme = "geo-engine"
preferred-dark-theme = "geo-engine"
mathjax-support = true
